aho odori^^
nkhs-ha05hc42/hc42-1026-git-work4-1 pull request #1
Opened 2024-11-18 02:48 UTC by huna-dayo

レビューをお願いします。

2024-11-18 02:57 UTC, shindai0524 requested changes

2024-11-18 02:57 UTC, shindai0524 commented on review.txt
> + review test1
はよ直したいいんちゃいますの
どないですのほんまに

2024-11-18 03:12 UTC, huna-dayo commented on review.txt
> + review test1
@shindai0524 
指摘箇所修正完了しています。

2024-11-25 00:40 UTC, shindai0524 approved these changes
修正確認しました！
LGTM!!

2024-11-25 00:42 UTC, merged

2024-11-25 00:43 UTC, huna-dayo reviewed
レモンサワー馬！！！！！

2024-11-25 00:45 UTC, huna-dayo commented on review.txt
> + review test1
みてます。